create extension if not exists "pg_cron" with schema "pg_catalog";

drop extension if exists "pg_net";

create type "public"."ad_status_enum" as enum ('active', 'paused', 'expired');

create type "public"."ad_type_enum" as enum ('video_overlay_top', 'video_overlay_center', 'video_pause_popup', 'interstitial', 'comment_section_ad', 'feed_inline', 'video_overlay_bottom');


  create table "public"."ads" (
    "id" uuid not null default gen_random_uuid(),
    "title" text not null,
    "content" text,
    "start_date" date,
    "end_date" date,
    "created_at" timestamp with time zone default now(),
    "ad_type" public.ad_type_enum not null default 'feed_inline'::public.ad_type_enum,
    "status" public.ad_status_enum not null default 'active'::public.ad_status_enum,
    "bg_color" text default '#1A0033'::text,
    "text_color" text default '#EDEDED'::text,
    "media_url" text,
    "link_url" text,
    "priority" integer default 0,
    "impressions" integer default 0,
    "clicks" integer default 0,
    "is_clickable" boolean default true,
    "created_by" uuid,
    "comment_image_url" text
      );


alter table "public"."ads" enable row level security;


  create table "public"."comments" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "post_id" uuid not null,
    "user_id" uuid not null,
    "comment" text not null,
    "likes_count" smallint not null default 0,
    "image_url" text,
    "video_part_id" uuid
      );


alter table "public"."comments" enable row level security;


  create table "public"."creator_requests" (
    "id" uuid not null default gen_random_uuid(),
    "user_id" uuid not null,
    "creator_username" text not null,
    "platform_title" text not null,
    "platform_description" text,
    "status" text not null default 'pending'::text,
    "created_at" timestamp with time zone default now(),
    "creator_avatar_url" text
      );


alter table "public"."creator_requests" enable row level security;


  create table "public"."likes" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "post_id" uuid,
    "user_id" uuid,
    "comment_id" bigint,
    "video_part_id" uuid
      );


alter table "public"."likes" enable row level security;


  create table "public"."payouts" (
    "id" uuid not null default gen_random_uuid(),
    "user_id" uuid,
    "amount" numeric(10,2) not null,
    "status" text default 'pending'::text,
    "created_at" timestamp with time zone default now()
      );



  create table "public"."post_views" (
    "id" uuid not null default gen_random_uuid(),
    "post_id" uuid,
    "viewer_id" uuid,
    "viewed_at" timestamp with time zone default now(),
    "video_part_id" uuid,
    "anon_id" uuid
      );


alter table "public"."post_views" enable row level security;


  create table "public"."posts" (
    "id" uuid not null default gen_random_uuid(),
    "caption" text not null,
    "topic" text not null,
    "song_name" text,
    "company" text,
    "video_url" text not null,
    "created_at" timestamp without time zone not null default now(),
    "updated_at" timestamp without time zone not null default now(),
    "user_id" uuid not null default auth.uid(),
    "comments_count" integer default 0,
    "likes_count" integer default 0,
    "views_count" integer not null default 0,
    "is_hidden" boolean default false,
    "thumbnail_url" text
      );


alter table "public"."posts" enable row level security;


  create table "public"."reports" (
    "id" uuid not null default gen_random_uuid(),
    "user_id" uuid,
    "target_id" uuid not null,
    "type" text not null,
    "status" text default 'pending'::text,
    "created_at" timestamp with time zone default now(),
    "reason" text,
    "reason_code" text,
    "reviewed_by" uuid,
    "reviewed_at" timestamp with time zone,
    "resolution" text
      );


alter table "public"."reports" enable row level security;


  create table "public"."subscriptions" (
    "id" uuid not null default gen_random_uuid(),
    "subscriber_id" uuid not null,
    "creator_id" uuid not null,
    "created_at" timestamp with time zone default now()
      );


alter table "public"."subscriptions" enable row level security;


  create table "public"."topics" (
    "id" uuid not null default gen_random_uuid(),
    "name" text not null,
    "total_posts" integer not null default 0,
    "created_at" timestamp without time zone default now(),
    "updated_at" timestamp without time zone default now()
      );


alter table "public"."topics" enable row level security;


  create table "public"."users" (
    "id" uuid not null,
    "username" text,
    "full_name" text,
    "avatar_url" text,
    "email" text,
    "created_at" timestamp with time zone default now(),
    "updated_at" timestamp with time zone default now(),
    "posts_count" integer default 0,
    "comments_count" integer default 0,
    "likes_count" integer default 0,
    "is_admin" boolean not null default false,
    "is_creator" boolean not null default false,
    "password" text,
    "subscribers_count" integer default 0,
    "subscriptions_count" integer default 0,
    "creator_username" text,
    "platform_title" text,
    "videos_watched" integer not null default 0,
    "creator_views" integer not null default 0,
    "creator_description" text,
    "creator_avatar_url" text,
    "is_adult" boolean default false
      );


alter table "public"."users" enable row level security;


  create table "public"."video_parts" (
    "id" uuid not null default gen_random_uuid(),
    "post_id" uuid not null,
    "part_number" integer not null,
    "video_url" text not null,
    "duration" numeric not null,
    "created_at" timestamp without time zone default now(),
    "user_id" uuid,
    "likes_count" integer default 0,
    "comments_count" integer default 0,
    "views_count" integer default 0,
    "thumbnail_url" text
      );


alter table "public"."video_parts" enable row level security;

CREATE UNIQUE INDEX ads_pkey ON public.ads USING btree (id);

CREATE UNIQUE INDEX anon_single_view_index ON public.post_views USING btree (anon_id, COALESCE(post_id, video_part_id)) WHERE (anon_id IS NOT NULL);

CREATE UNIQUE INDEX comments_pkey ON public.comments USING btree (id);

CREATE UNIQUE INDEX creator_requests_pkey ON public.creator_requests USING btree (id);

CREATE INDEX idx_post_views_video_part ON public.post_views USING btree (video_part_id);

CREATE INDEX idx_posts_user_id ON public.posts USING btree (user_id);

CREATE INDEX idx_posts_views_count ON public.posts USING btree (views_count);

CREATE UNIQUE INDEX likes_pkey ON public.likes USING btree (id);

CREATE UNIQUE INDEX likes_unique_comment ON public.likes USING btree (user_id, comment_id) WHERE (comment_id IS NOT NULL);

CREATE UNIQUE INDEX likes_unique_comment_user ON public.likes USING btree (comment_id, user_id) WHERE (comment_id IS NOT NULL);

CREATE UNIQUE INDEX likes_unique_post ON public.likes USING btree (user_id, post_id) WHERE (post_id IS NOT NULL);

CREATE UNIQUE INDEX likes_unique_post_user ON public.likes USING btree (post_id, user_id) WHERE (post_id IS NOT NULL);

CREATE UNIQUE INDEX likes_unique_target ON public.likes USING btree (user_id, COALESCE(post_id, video_part_id));

CREATE UNIQUE INDEX likes_unique_user_post ON public.likes USING btree (user_id, post_id) WHERE ((post_id IS NOT NULL) AND (video_part_id IS NULL));

CREATE UNIQUE INDEX likes_unique_user_video_part ON public.likes USING btree (user_id, video_part_id) WHERE (video_part_id IS NOT NULL);

CREATE UNIQUE INDEX payouts_pkey ON public.payouts USING btree (id);

CREATE UNIQUE INDEX post_views_pkey ON public.post_views USING btree (id);

CREATE UNIQUE INDEX post_views_post_id_viewer_id_key ON public.post_views USING btree (post_id, viewer_id);

CREATE UNIQUE INDEX posts_pkey ON public.posts USING btree (id);

CREATE UNIQUE INDEX reports_pkey ON public.reports USING btree (id);

CREATE UNIQUE INDEX reports_unique_user_target ON public.reports USING btree (user_id, target_id);

CREATE UNIQUE INDEX subscriptions_pkey ON public.subscriptions USING btree (id);

CREATE UNIQUE INDEX subscriptions_subscriber_id_creator_id_key ON public.subscriptions USING btree (subscriber_id, creator_id);

CREATE UNIQUE INDEX topics_name_key ON public.topics USING btree (name);

CREATE UNIQUE INDEX topics_pkey ON public.topics USING btree (id);

CREATE UNIQUE INDEX unique_post_view ON public.post_views USING btree (post_id, viewer_id);

CREATE UNIQUE INDEX users_creator_description_key ON public.users USING btree (creator_description);

CREATE UNIQUE INDEX users_creator_username_key ON public.users USING btree (creator_username);

CREATE UNIQUE INDEX users_email_key ON public.users USING btree (email);

CREATE UNIQUE INDEX users_pkey ON public.users USING btree (id);

CREATE UNIQUE INDEX users_platform_title_key ON public.users USING btree (platform_title);

CREATE UNIQUE INDEX users_username_key ON public.users USING btree (username);

CREATE UNIQUE INDEX video_parts_pkey ON public.video_parts USING btree (id);

alter table "public"."ads" add constraint "ads_pkey" PRIMARY KEY using index "ads_pkey";

alter table "public"."comments" add constraint "comments_pkey" PRIMARY KEY using index "comments_pkey";

alter table "public"."creator_requests" add constraint "creator_requests_pkey" PRIMARY KEY using index "creator_requests_pkey";

alter table "public"."likes" add constraint "likes_pkey" PRIMARY KEY using index "likes_pkey";

alter table "public"."payouts" add constraint "payouts_pkey" PRIMARY KEY using index "payouts_pkey";

alter table "public"."post_views" add constraint "post_views_pkey" PRIMARY KEY using index "post_views_pkey";

alter table "public"."posts" add constraint "posts_pkey" PRIMARY KEY using index "posts_pkey";

alter table "public"."reports" add constraint "reports_pkey" PRIMARY KEY using index "reports_pkey";

alter table "public"."subscriptions" add constraint "subscriptions_pkey" PRIMARY KEY using index "subscriptions_pkey";

alter table "public"."topics" add constraint "topics_pkey" PRIMARY KEY using index "topics_pkey";

alter table "public"."users" add constraint "users_pkey" PRIMARY KEY using index "users_pkey";

alter table "public"."video_parts" add constraint "video_parts_pkey" PRIMARY KEY using index "video_parts_pkey";

alter table "public"."ads" add constraint "ads_created_by_fkey" FOREIGN KEY (created_by) REFERENCES public.users(id) not valid;

alter table "public"."ads" validate constraint "ads_created_by_fkey";

alter table "public"."comments" add constraint "comments_post_id_fkey" FOREIGN KEY (post_id) REFERENCES public.posts(id) ON DELETE CASCADE not valid;

alter table "public"."comments" validate constraint "comments_post_id_fkey";

alter table "public"."comments" add constraint "comments_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE not valid;

alter table "public"."comments" validate constraint "comments_user_id_fkey";

alter table "public"."comments" add constraint "comments_video_part_fkey" FOREIGN KEY (video_part_id) REFERENCES public.video_parts(id) not valid;

alter table "public"."comments" validate constraint "comments_video_part_fkey";

alter table "public"."creator_requests" add constraint "creator_requests_status_check" CHECK ((status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text]))) not valid;

alter table "public"."creator_requests" validate constraint "creator_requests_status_check";

alter table "public"."creator_requests" add constraint "creator_requests_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE not valid;

alter table "public"."creator_requests" validate constraint "creator_requests_user_id_fkey";

alter table "public"."likes" add constraint "likes_comment_id_fkey" FOREIGN KEY (comment_id) REFERENCES public.comments(id) ON DELETE CASCADE not valid;

alter table "public"."likes" validate constraint "likes_comment_id_fkey";

alter table "public"."likes" add constraint "likes_post_id_fkey" FOREIGN KEY (post_id) REFERENCES public.posts(id) ON DELETE CASCADE not valid;

alter table "public"."likes" validate constraint "likes_post_id_fkey";

alter table "public"."likes" add constraint "likes_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE not valid;

alter table "public"."likes" validate constraint "likes_user_id_fkey";

alter table "public"."likes" add constraint "likes_video_part_id_fkey" FOREIGN KEY (video_part_id) REFERENCES public.video_parts(id) ON DELETE CASCADE not valid;

alter table "public"."likes" validate constraint "likes_video_part_id_fkey";

alter table "public"."payouts" add constraint "payouts_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.users(id) not valid;

alter table "public"."payouts" validate constraint "payouts_user_id_fkey";

alter table "public"."post_views" add constraint "post_views_post_id_fkey" FOREIGN KEY (post_id) REFERENCES public.posts(id) ON DELETE CASCADE not valid;

alter table "public"."post_views" validate constraint "post_views_post_id_fkey";

alter table "public"."post_views" add constraint "post_views_post_id_viewer_id_key" UNIQUE using index "post_views_post_id_viewer_id_key";

alter table "public"."post_views" add constraint "post_views_video_part_id_fkey" FOREIGN KEY (video_part_id) REFERENCES public.video_parts(id) ON DELETE CASCADE not valid;

alter table "public"."post_views" validate constraint "post_views_video_part_id_fkey";

alter table "public"."post_views" add constraint "post_views_viewer_id_fkey" FOREIGN KEY (viewer_id) REFERENCES public.users(id) ON DELETE CASCADE not valid;

alter table "public"."post_views" validate constraint "post_views_viewer_id_fkey";

alter table "public"."post_views" add constraint "unique_post_view" UNIQUE using index "unique_post_view";

alter table "public"."posts" add constraint "posts_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.users(id) not valid;

alter table "public"."posts" validate constraint "posts_user_id_fkey";

alter table "public"."reports" add constraint "reports_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.users(id) not valid;

alter table "public"."reports" validate constraint "reports_user_id_fkey";

alter table "public"."subscriptions" add constraint "no_self_subscribe" CHECK ((subscriber_id <> creator_id)) not valid;

alter table "public"."subscriptions" validate constraint "no_self_subscribe";

alter table "public"."subscriptions" add constraint "subscriptions_creator_id_fkey" FOREIGN KEY (creator_id) REFERENCES public.users(id) ON DELETE CASCADE not valid;

alter table "public"."subscriptions" validate constraint "subscriptions_creator_id_fkey";

alter table "public"."subscriptions" add constraint "subscriptions_subscriber_id_creator_id_key" UNIQUE using index "subscriptions_subscriber_id_creator_id_key";

alter table "public"."subscriptions" add constraint "subscriptions_subscriber_id_fkey" FOREIGN KEY (subscriber_id) REFERENCES public.users(id) ON DELETE CASCADE not valid;

alter table "public"."subscriptions" validate constraint "subscriptions_subscriber_id_fkey";

alter table "public"."topics" add constraint "topics_name_key" UNIQUE using index "topics_name_key";

alter table "public"."users" add constraint "creator_fields_check" CHECK (((is_creator = true) OR ((creator_username IS NULL) AND (platform_title IS NULL)))) not valid;

alter table "public"."users" validate constraint "creator_fields_check";

alter table "public"."users" add constraint "username_length" CHECK ((char_length(username) >= 3)) not valid;

alter table "public"."users" validate constraint "username_length";

alter table "public"."users" add constraint "users_creator_description_key" UNIQUE using index "users_creator_description_key";

alter table "public"."users" add constraint "users_creator_username_key" UNIQUE using index "users_creator_username_key";

alter table "public"."users" add constraint "users_email_key" UNIQUE using index "users_email_key";

alter table "public"."users" add constraint "users_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."users" validate constraint "users_id_fkey";

alter table "public"."users" add constraint "users_platform_title_key" UNIQUE using index "users_platform_title_key";

alter table "public"."users" add constraint "users_username_key" UNIQUE using index "users_username_key";

alter table "public"."video_parts" add constraint "video_parts_post_id_fkey" FOREIGN KEY (post_id) REFERENCES public.posts(id) ON DELETE CASCADE not valid;

alter table "public"."video_parts" validate constraint "video_parts_post_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.add_anon_view(p_anon_id uuid, p_post_id uuid, p_video_part_id uuid)
 RETURNS void
 LANGUAGE plpgsql
AS $function$
BEGIN
    -- Only insert if no existing row matches anon_id + post_id or anon_id + video_part_id
    INSERT INTO public.post_views (anon_id, post_id, video_part_id)
    SELECT p_anon_id, p_post_id, p_video_part_id
    WHERE NOT EXISTS (
        SELECT 1
        FROM public.post_views pv
        WHERE pv.anon_id = p_anon_id
          AND (
                (p_post_id IS NOT NULL AND pv.post_id = p_post_id)
             OR (p_video_part_id IS NOT NULL AND pv.video_part_id = p_video_part_id)
          )
    );
END;
$function$
;

CREATE OR REPLACE FUNCTION public.decrement_comment_like_count()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
  -- Only decrement if comment_id is provided
  IF OLD.comment_id IS NOT NULL THEN
    UPDATE public.comments
    SET like_count = like_count - 1
    WHERE id = OLD.comment_id;
  END IF;
  RETURN OLD;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
begin
  insert into public.users (id, full_name, avatar_url, email)
  values (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url', new.email);
  return new;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.handle_post_view_delete()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  post_owner uuid;
begin
  select user_id into post_owner
  from posts
  where id = old.post_id;

  if old.viewer_id = post_owner then
    return old;
  end if;

  update posts
  set views_count = views_count - 1
  where id = old.post_id;

  update users
  set videos_watched = videos_watched - 1
  where id = old.viewer_id;

  update users
  set creator_views = creator_views - 1
  where id = post_owner;

  return old;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.handle_post_view_insert()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  post_owner uuid;
begin

  select user_id into post_owner
  from posts
  where id = new.post_id;

  if new.viewer_id = post_owner then
    return new;
  end if;

  update posts
  set views_count = views_count + 1
  where id = new.post_id;

  update users
  set videos_watched = videos_watched + 1
  where id = new.viewer_id;

  update users
  set creator_views = creator_views + 1
  where id = post_owner;

  return new;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.handle_subscription_count()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
begin
  if tg_op = 'INSERT' then
    update users
    set subscribers_count = subscribers_count + 1
    where id = new.creator_id;

    update users
    set subscriptions_count = subscriptions_count + 1
    where id = new.subscriber_id;

  elsif tg_op = 'DELETE' then
    update users
    set subscribers_count = subscribers_count - 1
    where id = old.creator_id;

    update users
    set subscriptions_count = subscriptions_count - 1
    where id = old.subscriber_id;
  end if;

  return null;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.increment_comment_like_count()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
  -- Only increment if comment_id is provided
  IF NEW.comment_id IS NOT NULL THEN
    UPDATE public.comments
    SET like_count = like_count + 1
    WHERE id = NEW.comment_id;
  END IF;
  RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.increment_comments_count()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
begin
  update public.posts
  set comments_count = comments_count + 1
  where id = new.post_id;
  return new;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.increment_post_views(p_post_id text, p_viewer_id text, p_creator_id text)
 RETURNS void
 LANGUAGE plpgsql
AS $function$
begin
  insert into post_views(post_id, viewer_id)
  values (p_post_id::uuid, p_viewer_id::uuid)
  on conflict (post_id, viewer_id) do nothing;

  update posts
  set views_count = (
      select count(*) from post_views where post_id = p_post_id::uuid
  )
  where id = p_post_id::uuid;

  update users
  set creator_views = (
      select coalesce(sum(views_count),0) from posts where user_id = p_creator_id::uuid
  )
  where id = p_creator_id::uuid;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.increment_post_views_anonymous(p_post_id uuid, p_anon_id uuid, p_video_part_id uuid DEFAULT NULL::uuid)
 RETURNS void
 LANGUAGE plpgsql
AS $function$
declare
  already_viewed boolean;
begin
  select exists (
    select 1
    from post_views
    where post_id = p_post_id
      and anonymous_views ->> 'anon_id' = p_anon_id::text
  ) into already_viewed;

  if already_viewed then
    raise notice 'ANON VIEW SKIPPED %', p_anon_id;
    return;
  end if;

  insert into post_views (
    post_id,
    video_part_id,
    anonymous_views
  )
  values (
    p_post_id,
    p_video_part_id,
    jsonb_build_object('anon_id', p_anon_id)
  );

  update posts
  set views_count = views_count + 1
  where id = p_post_id;

  raise notice 'ANON VIEW SAVED %', p_anon_id;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.increment_view_counts(p_post_id text, p_viewer_id text, p_creator_id text)
 RETURNS void
 LANGUAGE plpgsql
AS $function$
begin
  insert into post_views(post_id, viewer_id)
  values (p_post_id::uuid, p_viewer_id::uuid)
  on conflict (post_id, viewer_id) do nothing;

  update posts
  set views_count = (
      select count(*) from post_views where post_id = p_post_id::uuid
  )
  where id = p_post_id::uuid;

  update users
  set creator_views = (
      select coalesce(sum(views_count),0) from posts where user_id = p_creator_id::uuid
  )
  where id = p_creator_id::uuid;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.increment_view_counts(p_post_id uuid, p_video_part_id uuid, p_viewer_id uuid, p_creator_id uuid)
 RETURNS void
 LANGUAGE plpgsql
AS $function$
begin

  IF p_video_part_id IS NOT NULL THEN

    insert into post_views(video_part_id, viewer_id, viewed_at)
    values (p_video_part_id, p_viewer_id, now())
    on conflict do nothing;

    update video_parts
    set views_count = (
      select count(*) from post_views where video_part_id = p_video_part_id
    )
    where id = p_video_part_id;

    RAISE LOG 'VIDEO PART VIEW COUNT UPDATED %', p_video_part_id;

  ELSE

    insert into post_views(post_id, viewer_id, viewed_at)
    values (p_post_id, p_viewer_id, now())
    on conflict do nothing;

    update posts
    set views_count = (
      select count(*) from post_views where post_id = p_post_id
    )
    where id = p_post_id;

    RAISE LOG 'POST VIEW COUNT UPDATED %', p_post_id;

  END IF;


  update users
  set creator_views = (
    select coalesce(sum(views_count),0)
    from posts
    where user_id = p_creator_id
  )
  where id = p_creator_id;

end;
$function$
;

CREATE OR REPLACE FUNCTION public.increment_view_counts(p_post_id uuid, p_viewer_id uuid, p_creator_id uuid)
 RETURNS void
 LANGUAGE plpgsql
AS $function$
begin
  insert into post_views(post_id, viewer_id, viewed_at)
    values (p_post_id, p_viewer_id, now())
    on conflict do nothing;

  update posts
    set views_count = (select count(*) from post_views where post_id = p_post_id)
    where id = p_post_id;

  update users
    set videos_watched = (select count(*) from post_views where viewer_id = p_viewer_id)
    where id = p_viewer_id;

  update users
    set creator_views = (select coalesce(sum(views_count),0) from posts where user_id = p_creator_id)
    where id = p_creator_id;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.periodic_resync_counts()
 RETURNS void
 LANGUAGE plpgsql
AS $function$
BEGIN
    -- Step 1: Aggregate single-word topics from posts and video_parts
    WITH post_topics AS (
        SELECT unnest(string_to_array(topic, ' ')) AS topic_name
        FROM posts
        WHERE topic IS NOT NULL
    ),
    video_part_topics AS (
        SELECT unnest(string_to_array(p.topic, ' ')) AS topic_name
        FROM video_parts vp
        JOIN posts p ON vp.post_id = p.id
        WHERE p.topic IS NOT NULL
    ),
    combined AS (
        SELECT LOWER(topic_name) AS topic_name, COUNT(*) AS total_posts
        FROM (
            SELECT topic_name FROM post_topics
            UNION ALL
            SELECT topic_name FROM video_part_topics
        ) t
        WHERE topic_name NOT LIKE '% %'   -- Ignore multi-word topics
          AND topic_name <> ''            -- Ignore empty strings
        GROUP BY LOWER(topic_name)
    )
    -- Step 2: Upsert into topics table
    INSERT INTO topics (name, total_posts, created_at, updated_at)
    SELECT topic_name, total_posts, now(), now()
    FROM combined
    ON CONFLICT (name) 
    DO UPDATE SET total_posts = EXCLUDED.total_posts, updated_at = now();
END;
$function$
;

create or replace view "public"."public_profiles" as  SELECT id,
    username,
    avatar_url,
    posts_count,
    likes_count,
    is_creator,
    subscribers_count
   FROM public.users;


CREATE OR REPLACE FUNCTION public.recalc_comments_all()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
begin
  -- update post comments count
  if coalesce(new.post_id, old.post_id) is not null then
    update posts
    set comments_count = (
      select count(*) from comments c where c.post_id = coalesce(new.post_id, old.post_id)
    )
    where id = coalesce(new.post_id, old.post_id);
  end if;

  -- update video_parts comments count
  if coalesce(new.video_part_id, old.video_part_id) is not null then
    update video_parts
    set comments_count = (
      select count(*) from comments c where c.video_part_id = coalesce(new.video_part_id, old.video_part_id)
    )
    where id = coalesce(new.video_part_id, old.video_part_id);
  end if;

  return coalesce(new, old);
end;
$function$
;

CREATE OR REPLACE FUNCTION public.recalc_likes_all()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
begin
  -- update post likes count
  if coalesce(new.post_id, old.post_id) is not null then
    update posts
    set likes_count = (
      select count(*) from likes l where l.post_id = coalesce(new.post_id, old.post_id)
    )
    where id = coalesce(new.post_id, old.post_id);
  end if;

  -- update video_parts likes count
  if coalesce(new.video_part_id, old.video_part_id) is not null then
    update video_parts
    set likes_count = (
      select count(*) from likes l where l.video_part_id = coalesce(new.video_part_id, old.video_part_id)
    )
    where id = coalesce(new.video_part_id, old.video_part_id);
  end if;

  return coalesce(new, old);
end;
$function$
;

CREATE OR REPLACE FUNCTION public.recalc_post_views()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
begin
  update posts
  set views_count = (
    select count(*)
    from post_views pv
    where pv.post_id = new.post_id
  )
  where id = new.post_id;

  return new;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.recalc_views_all()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
begin
  -- update user videos watched
  update users
  set videos_watched = (
    select count(distinct pv.post_id)
    from post_views pv
    where pv.viewer_id = coalesce(new.viewer_id, old.viewer_id)
  )
  where id = coalesce(new.viewer_id, old.viewer_id);

  -- update post views count
  update posts
  set views_count = (
    select count(*)
    from post_views pv
    where pv.post_id = coalesce(new.post_id, old.post_id)
  )
  where id = coalesce(new.post_id, old.post_id);

  -- update creator views
  update users
  set creator_views = (
    select coalesce(sum(p.views_count),0)
    from posts p
    where p.user_id = (
      select user_id from posts where id = coalesce(new.post_id, old.post_id)
    )
  )
  where id = (
    select user_id from posts where id = coalesce(new.post_id, old.post_id)
  );

  return coalesce(new, old);
end;
$function$
;

CREATE OR REPLACE FUNCTION public.sync_creator_request_to_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
begin
  -- APPROVED → enable creator
  if new.status = 'approved'
     and old.status is distinct from 'approved' then

    update public.users
    set
      is_creator = true,
      creator_username = new.creator_username,
      platform_title = new.platform_title,
      creator_description = new.platform_description,
      creator_avatar_url = new.creator_avatar_url,
      updated_at = now()
    where id = new.user_id;

  -- REVOKED / REJECTED → disable creator
  elsif new.status in ('rejected', 'revoked')
        and old.status is distinct from new.status then

    update public.users
    set
      is_creator = false,
      creator_username = null,
      platform_title = null,
      creator_description = null,
      creator_avatar_url = null,
      updated_at = now()
    where id = new.user_id;

  end if;

  return new;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.sync_creator_status()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
    if new.status = 'approved' then
        update users
        set is_creator = true
        where id = new.user_id;

    elsif new.status = 'rejected' then
        update users
        set is_creator = false
        where id = new.user_id;
    end if;

    return new;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.update_comment_likes_count()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
  IF TG_OP = 'INSERT' THEN
    IF NEW.comment_id IS NOT NULL THEN
      UPDATE public.comments
      SET likes_count = likes_count + 1
      WHERE id = NEW.comment_id;
    END IF;
  ELSIF TG_OP = 'DELETE' THEN
    IF OLD.comment_id IS NOT NULL THEN
      UPDATE public.comments
      SET likes_count = likes_count - 1
      WHERE id = OLD.comment_id;
    END IF;
  END IF;
  RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.update_post_comments_count()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN

  IF TG_OP = 'INSERT' THEN

    IF NEW.video_part_id IS NOT NULL THEN
      UPDATE video_parts
      SET comments_count = comments_count + 1
      WHERE id = NEW.video_part_id;

      RAISE LOG 'VIDEO PART COMMENT INSERT';

    ELSE
      UPDATE posts
      SET comments_count = comments_count + 1
      WHERE id = NEW.post_id;

      RAISE LOG 'POST COMMENT INSERT';
    END IF;

  END IF;


  IF TG_OP = 'DELETE' THEN

    IF OLD.video_part_id IS NOT NULL THEN
      UPDATE video_parts
      SET comments_count = comments_count - 1
      WHERE id = OLD.video_part_id;

      RAISE LOG 'VIDEO PART COMMENT DELETE';

    ELSE
      UPDATE posts
      SET comments_count = comments_count - 1
      WHERE id = OLD.post_id;

      RAISE LOG 'POST COMMENT DELETE';
    END IF;

  END IF;

  RETURN NEW;

END;
$function$
;

CREATE OR REPLACE FUNCTION public.update_post_likes_count()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN

  IF TG_OP = 'INSERT' THEN

    IF NEW.video_part_id IS NOT NULL THEN
      UPDATE video_parts
      SET likes_count = likes_count + 1
      WHERE id = NEW.video_part_id;

      RAISE LOG 'VIDEO PART LIKE INSERT → COUNT +1 %', NEW.video_part_id;

    ELSE
      UPDATE posts
      SET likes_count = likes_count + 1
      WHERE id = NEW.post_id;

      RAISE LOG 'POST LIKE INSERT → COUNT +1 %', NEW.post_id;
    END IF;

  END IF;


  IF TG_OP = 'DELETE' THEN

    IF OLD.video_part_id IS NOT NULL THEN
      UPDATE video_parts
      SET likes_count = GREATEST(likes_count - 1,0)
      WHERE id = OLD.video_part_id;

      RAISE LOG 'VIDEO PART LIKE DELETE → COUNT -1 %', OLD.video_part_id;

    ELSE
      UPDATE posts
      SET likes_count = GREATEST(likes_count - 1,0)
      WHERE id = OLD.post_id;

      RAISE LOG 'POST LIKE DELETE → COUNT -1 %', OLD.post_id;
    END IF;

  END IF;

  RETURN NULL;

END;
$function$
;

CREATE OR REPLACE FUNCTION public.update_user_comments_count()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
  IF TG_OP = 'INSERT' THEN
    UPDATE public.users SET comments_count = comments_count + 1 WHERE id = NEW.user_id;
  ELSIF TG_OP = 'DELETE' THEN
    UPDATE public.users SET comments_count = comments_count - 1 WHERE id = OLD.user_id;
  END IF;
  RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.update_user_creator_status()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
begin
  if new.status = 'approved' then
    update users
    set is_creator = true,
        creator_username = new.creator_username,
        platform_title = new.platform_title,
        creator_description = new.platform_description,
        updated_at = now()
    where id = new.user_id;
  end if;

  if new.status = 'rejected' then
    update users
    set is_creator = false,
        updated_at = now()
    where id = new.user_id;
  end if;

  return new;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.update_user_likes_count()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
  IF TG_OP = 'INSERT' THEN
    UPDATE public.users SET likes_count = likes_count + 1 WHERE id = NEW.user_id;
  ELSIF TG_OP = 'DELETE' THEN
    UPDATE public.users SET likes_count = likes_count - 1 WHERE id = OLD.user_id;
  END IF;
  RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.update_user_posts_count()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
  IF TG_OP = 'INSERT' THEN
    UPDATE public.users SET posts_count = posts_count + 1 WHERE id = NEW.user_id;
  ELSIF TG_OP = 'DELETE' THEN
    UPDATE public.users SET posts_count = posts_count - 1 WHERE id = OLD.user_id;
  END IF;
  RETURN NEW;
END;
$function$
;

grant delete on table "public"."ads" to "anon";

grant insert on table "public"."ads" to "anon";

grant references on table "public"."ads" to "anon";

grant select on table "public"."ads" to "anon";

grant trigger on table "public"."ads" to "anon";

grant truncate on table "public"."ads" to "anon";

grant update on table "public"."ads" to "anon";

grant delete on table "public"."ads" to "authenticated";

grant insert on table "public"."ads" to "authenticated";

grant references on table "public"."ads" to "authenticated";

grant select on table "public"."ads" to "authenticated";

grant trigger on table "public"."ads" to "authenticated";

grant truncate on table "public"."ads" to "authenticated";

grant update on table "public"."ads" to "authenticated";

grant delete on table "public"."ads" to "service_role";

grant insert on table "public"."ads" to "service_role";

grant references on table "public"."ads" to "service_role";

grant select on table "public"."ads" to "service_role";

grant trigger on table "public"."ads" to "service_role";

grant truncate on table "public"."ads" to "service_role";

grant update on table "public"."ads" to "service_role";

grant delete on table "public"."comments" to "anon";

grant insert on table "public"."comments" to "anon";

grant references on table "public"."comments" to "anon";

grant select on table "public"."comments" to "anon";

grant trigger on table "public"."comments" to "anon";

grant truncate on table "public"."comments" to "anon";

grant update on table "public"."comments" to "anon";

grant delete on table "public"."comments" to "authenticated";

grant insert on table "public"."comments" to "authenticated";

grant references on table "public"."comments" to "authenticated";

grant select on table "public"."comments" to "authenticated";

grant trigger on table "public"."comments" to "authenticated";

grant truncate on table "public"."comments" to "authenticated";

grant update on table "public"."comments" to "authenticated";

grant delete on table "public"."comments" to "service_role";

grant insert on table "public"."comments" to "service_role";

grant references on table "public"."comments" to "service_role";

grant select on table "public"."comments" to "service_role";

grant trigger on table "public"."comments" to "service_role";

grant truncate on table "public"."comments" to "service_role";

grant update on table "public"."comments" to "service_role";

grant delete on table "public"."creator_requests" to "anon";

grant insert on table "public"."creator_requests" to "anon";

grant references on table "public"."creator_requests" to "anon";

grant select on table "public"."creator_requests" to "anon";

grant trigger on table "public"."creator_requests" to "anon";

grant truncate on table "public"."creator_requests" to "anon";

grant update on table "public"."creator_requests" to "anon";

grant delete on table "public"."creator_requests" to "authenticated";

grant insert on table "public"."creator_requests" to "authenticated";

grant references on table "public"."creator_requests" to "authenticated";

grant select on table "public"."creator_requests" to "authenticated";

grant trigger on table "public"."creator_requests" to "authenticated";

grant truncate on table "public"."creator_requests" to "authenticated";

grant update on table "public"."creator_requests" to "authenticated";

grant delete on table "public"."creator_requests" to "service_role";

grant insert on table "public"."creator_requests" to "service_role";

grant references on table "public"."creator_requests" to "service_role";

grant select on table "public"."creator_requests" to "service_role";

grant trigger on table "public"."creator_requests" to "service_role";

grant truncate on table "public"."creator_requests" to "service_role";

grant update on table "public"."creator_requests" to "service_role";

grant delete on table "public"."likes" to "anon";

grant insert on table "public"."likes" to "anon";

grant references on table "public"."likes" to "anon";

grant select on table "public"."likes" to "anon";

grant trigger on table "public"."likes" to "anon";

grant truncate on table "public"."likes" to "anon";

grant update on table "public"."likes" to "anon";

grant delete on table "public"."likes" to "authenticated";

grant insert on table "public"."likes" to "authenticated";

grant references on table "public"."likes" to "authenticated";

grant select on table "public"."likes" to "authenticated";

grant trigger on table "public"."likes" to "authenticated";

grant truncate on table "public"."likes" to "authenticated";

grant update on table "public"."likes" to "authenticated";

grant delete on table "public"."likes" to "service_role";

grant insert on table "public"."likes" to "service_role";

grant references on table "public"."likes" to "service_role";

grant select on table "public"."likes" to "service_role";

grant trigger on table "public"."likes" to "service_role";

grant truncate on table "public"."likes" to "service_role";

grant update on table "public"."likes" to "service_role";

grant delete on table "public"."payouts" to "anon";

grant insert on table "public"."payouts" to "anon";

grant references on table "public"."payouts" to "anon";

grant select on table "public"."payouts" to "anon";

grant trigger on table "public"."payouts" to "anon";

grant truncate on table "public"."payouts" to "anon";

grant update on table "public"."payouts" to "anon";

grant delete on table "public"."payouts" to "authenticated";

grant insert on table "public"."payouts" to "authenticated";

grant references on table "public"."payouts" to "authenticated";

grant select on table "public"."payouts" to "authenticated";

grant trigger on table "public"."payouts" to "authenticated";

grant truncate on table "public"."payouts" to "authenticated";

grant update on table "public"."payouts" to "authenticated";

grant delete on table "public"."payouts" to "service_role";

grant insert on table "public"."payouts" to "service_role";

grant references on table "public"."payouts" to "service_role";

grant select on table "public"."payouts" to "service_role";

grant trigger on table "public"."payouts" to "service_role";

grant truncate on table "public"."payouts" to "service_role";

grant update on table "public"."payouts" to "service_role";

grant delete on table "public"."post_views" to "anon";

grant insert on table "public"."post_views" to "anon";

grant references on table "public"."post_views" to "anon";

grant select on table "public"."post_views" to "anon";

grant trigger on table "public"."post_views" to "anon";

grant truncate on table "public"."post_views" to "anon";

grant update on table "public"."post_views" to "anon";

grant delete on table "public"."post_views" to "authenticated";

grant insert on table "public"."post_views" to "authenticated";

grant references on table "public"."post_views" to "authenticated";

grant select on table "public"."post_views" to "authenticated";

grant trigger on table "public"."post_views" to "authenticated";

grant truncate on table "public"."post_views" to "authenticated";

grant update on table "public"."post_views" to "authenticated";

grant delete on table "public"."post_views" to "service_role";

grant insert on table "public"."post_views" to "service_role";

grant references on table "public"."post_views" to "service_role";

grant select on table "public"."post_views" to "service_role";

grant trigger on table "public"."post_views" to "service_role";

grant truncate on table "public"."post_views" to "service_role";

grant update on table "public"."post_views" to "service_role";

grant delete on table "public"."posts" to "anon";

grant insert on table "public"."posts" to "anon";

grant references on table "public"."posts" to "anon";

grant select on table "public"."posts" to "anon";

grant trigger on table "public"."posts" to "anon";

grant truncate on table "public"."posts" to "anon";

grant update on table "public"."posts" to "anon";

grant delete on table "public"."posts" to "authenticated";

grant insert on table "public"."posts" to "authenticated";

grant references on table "public"."posts" to "authenticated";

grant select on table "public"."posts" to "authenticated";

grant trigger on table "public"."posts" to "authenticated";

grant truncate on table "public"."posts" to "authenticated";

grant update on table "public"."posts" to "authenticated";

grant delete on table "public"."posts" to "service_role";

grant insert on table "public"."posts" to "service_role";

grant references on table "public"."posts" to "service_role";

grant select on table "public"."posts" to "service_role";

grant trigger on table "public"."posts" to "service_role";

grant truncate on table "public"."posts" to "service_role";

grant update on table "public"."posts" to "service_role";

grant delete on table "public"."reports" to "anon";

grant insert on table "public"."reports" to "anon";

grant references on table "public"."reports" to "anon";

grant select on table "public"."reports" to "anon";

grant trigger on table "public"."reports" to "anon";

grant truncate on table "public"."reports" to "anon";

grant update on table "public"."reports" to "anon";

grant delete on table "public"."reports" to "authenticated";

grant insert on table "public"."reports" to "authenticated";

grant references on table "public"."reports" to "authenticated";

grant select on table "public"."reports" to "authenticated";

grant trigger on table "public"."reports" to "authenticated";

grant truncate on table "public"."reports" to "authenticated";

grant update on table "public"."reports" to "authenticated";

grant delete on table "public"."reports" to "service_role";

grant insert on table "public"."reports" to "service_role";

grant references on table "public"."reports" to "service_role";

grant select on table "public"."reports" to "service_role";

grant trigger on table "public"."reports" to "service_role";

grant truncate on table "public"."reports" to "service_role";

grant update on table "public"."reports" to "service_role";

grant delete on table "public"."subscriptions" to "anon";

grant insert on table "public"."subscriptions" to "anon";

grant references on table "public"."subscriptions" to "anon";

grant select on table "public"."subscriptions" to "anon";

grant trigger on table "public"."subscriptions" to "anon";

grant truncate on table "public"."subscriptions" to "anon";

grant update on table "public"."subscriptions" to "anon";

grant delete on table "public"."subscriptions" to "authenticated";

grant insert on table "public"."subscriptions" to "authenticated";

grant references on table "public"."subscriptions" to "authenticated";

grant select on table "public"."subscriptions" to "authenticated";

grant trigger on table "public"."subscriptions" to "authenticated";

grant truncate on table "public"."subscriptions" to "authenticated";

grant update on table "public"."subscriptions" to "authenticated";

grant delete on table "public"."subscriptions" to "service_role";

grant insert on table "public"."subscriptions" to "service_role";

grant references on table "public"."subscriptions" to "service_role";

grant select on table "public"."subscriptions" to "service_role";

grant trigger on table "public"."subscriptions" to "service_role";

grant truncate on table "public"."subscriptions" to "service_role";

grant update on table "public"."subscriptions" to "service_role";

grant delete on table "public"."topics" to "anon";

grant insert on table "public"."topics" to "anon";

grant references on table "public"."topics" to "anon";

grant select on table "public"."topics" to "anon";

grant trigger on table "public"."topics" to "anon";

grant truncate on table "public"."topics" to "anon";

grant update on table "public"."topics" to "anon";

grant delete on table "public"."topics" to "authenticated";

grant insert on table "public"."topics" to "authenticated";

grant references on table "public"."topics" to "authenticated";

grant select on table "public"."topics" to "authenticated";

grant trigger on table "public"."topics" to "authenticated";

grant truncate on table "public"."topics" to "authenticated";

grant update on table "public"."topics" to "authenticated";

grant delete on table "public"."topics" to "service_role";

grant insert on table "public"."topics" to "service_role";

grant references on table "public"."topics" to "service_role";

grant select on table "public"."topics" to "service_role";

grant trigger on table "public"."topics" to "service_role";

grant truncate on table "public"."topics" to "service_role";

grant update on table "public"."topics" to "service_role";

grant delete on table "public"."users" to "anon";

grant insert on table "public"."users" to "anon";

grant references on table "public"."users" to "anon";

grant select on table "public"."users" to "anon";

grant trigger on table "public"."users" to "anon";

grant truncate on table "public"."users" to "anon";

grant update on table "public"."users" to "anon";

grant delete on table "public"."users" to "authenticated";

grant insert on table "public"."users" to "authenticated";

grant references on table "public"."users" to "authenticated";

grant select on table "public"."users" to "authenticated";

grant trigger on table "public"."users" to "authenticated";

grant truncate on table "public"."users" to "authenticated";

grant update on table "public"."users" to "authenticated";

grant delete on table "public"."users" to "service_role";

grant insert on table "public"."users" to "service_role";

grant references on table "public"."users" to "service_role";

grant select on table "public"."users" to "service_role";

grant trigger on table "public"."users" to "service_role";

grant truncate on table "public"."users" to "service_role";

grant update on table "public"."users" to "service_role";

grant delete on table "public"."video_parts" to "anon";

grant insert on table "public"."video_parts" to "anon";

grant references on table "public"."video_parts" to "anon";

grant select on table "public"."video_parts" to "anon";

grant trigger on table "public"."video_parts" to "anon";

grant truncate on table "public"."video_parts" to "anon";

grant update on table "public"."video_parts" to "anon";

grant delete on table "public"."video_parts" to "authenticated";

grant insert on table "public"."video_parts" to "authenticated";

grant references on table "public"."video_parts" to "authenticated";

grant select on table "public"."video_parts" to "authenticated";

grant trigger on table "public"."video_parts" to "authenticated";

grant truncate on table "public"."video_parts" to "authenticated";

grant update on table "public"."video_parts" to "authenticated";

grant delete on table "public"."video_parts" to "service_role";

grant insert on table "public"."video_parts" to "service_role";

grant references on table "public"."video_parts" to "service_role";

grant select on table "public"."video_parts" to "service_role";

grant trigger on table "public"."video_parts" to "service_role";

grant truncate on table "public"."video_parts" to "service_role";

grant update on table "public"."video_parts" to "service_role";


  create policy "Admins manage ads"
  on "public"."ads"
  as permissive
  for all
  to public
using ((EXISTS ( SELECT 1
   FROM public.users
  WHERE ((users.id = auth.uid()) AND (users.is_admin = true)))))
with check ((EXISTS ( SELECT 1
   FROM public.users
  WHERE ((users.id = auth.uid()) AND (users.is_admin = true)))));



  create policy "Public can view active ads"
  on "public"."ads"
  as permissive
  for select
  to public
using ((status = 'active'::public.ad_status_enum));



  create policy "Allow insert"
  on "public"."comments"
  as permissive
  for insert
  to public
with check ((auth.role() = 'authenticated'::text));



  create policy "Allow read"
  on "public"."comments"
  as permissive
  for select
  to public
using ((auth.role() = 'authenticated'::text));



  create policy "Anyone can read comments"
  on "public"."comments"
  as permissive
  for select
  to public
using (true);



  create policy "Logged in users can add comments"
  on "public"."comments"
  as permissive
  for insert
  to authenticated
with check ((auth.uid() = user_id));



  create policy "Users can delete own comments"
  on "public"."comments"
  as permissive
  for delete
  to authenticated
using ((auth.uid() = user_id));



  create policy "Users can update own comments"
  on "public"."comments"
  as permissive
  for update
  to authenticated
using ((auth.uid() = user_id));



  create policy "Admin can update creator requests"
  on "public"."creator_requests"
  as permissive
  for update
  to public
using ((EXISTS ( SELECT 1
   FROM public.users
  WHERE ((users.id = auth.uid()) AND (users.is_admin = true)))));



  create policy "admin can read all creator requests"
  on "public"."creator_requests"
  as permissive
  for select
  to public
using ((EXISTS ( SELECT 1
   FROM public.users
  WHERE ((users.id = auth.uid()) AND (users.is_admin = true)))));



  create policy "admin can update creator requests"
  on "public"."creator_requests"
  as permissive
  for update
  to public
using ((EXISTS ( SELECT 1
   FROM public.users
  WHERE ((users.id = auth.uid()) AND (users.is_admin = true)))));



  create policy "users can create own creator request"
  on "public"."creator_requests"
  as permissive
  for insert
  to public
with check ((auth.uid() = user_id));



  create policy "users can read own creator request"
  on "public"."creator_requests"
  as permissive
  for select
  to public
using ((auth.uid() = user_id));



  create policy "Allow insert"
  on "public"."likes"
  as permissive
  for insert
  to public
with check ((auth.role() = 'authenticated'::text));



  create policy "Allow read"
  on "public"."likes"
  as permissive
  for select
  to public
using ((auth.role() = 'authenticated'::text));



  create policy "users can delete their own likes"
  on "public"."likes"
  as permissive
  for delete
  to public
using ((auth.uid() = user_id));



  create policy "users can insert their own likes"
  on "public"."likes"
  as permissive
  for insert
  to public
with check ((auth.uid() = user_id));



  create policy "users can read likes"
  on "public"."likes"
  as permissive
  for select
  to public
using (true);



  create policy "anon can insert own views"
  on "public"."post_views"
  as permissive
  for insert
  to public
with check ((anon_id IS NOT NULL));



  create policy "anonymous update via rpc only"
  on "public"."post_views"
  as permissive
  for update
  to public
using (true)
with check (true);



  create policy "auth users insert own views"
  on "public"."post_views"
  as permissive
  for insert
  to authenticated
with check ((auth.uid() = viewer_id));



  create policy "auth users update own views"
  on "public"."post_views"
  as permissive
  for update
  to authenticated
using ((auth.uid() = viewer_id));



  create policy "public can read views"
  on "public"."post_views"
  as permissive
  for select
  to public
using (true);



  create policy "Allow creators to insert posts"
  on "public"."posts"
  as permissive
  for insert
  to public
with check ((EXISTS ( SELECT 1
   FROM public.users u
  WHERE ((u.id = auth.uid()) AND (u.is_creator = true)))));



  create policy "Allow insert for authenticated users"
  on "public"."posts"
  as permissive
  for insert
  to public
with check ((auth.uid() = user_id));



  create policy "Enable read access for all users"
  on "public"."posts"
  as permissive
  for select
  to public
using (true);



  create policy "admins can read reports"
  on "public"."reports"
  as permissive
  for select
  to public
using ((EXISTS ( SELECT 1
   FROM public.users
  WHERE ((users.id = auth.uid()) AND (users.is_admin = true)))));



  create policy "admins can update reports"
  on "public"."reports"
  as permissive
  for update
  to public
using ((EXISTS ( SELECT 1
   FROM public.users
  WHERE ((users.id = auth.uid()) AND (users.is_admin = true)))));



  create policy "logged in users can insert reports"
  on "public"."reports"
  as permissive
  for insert
  to public
with check ((auth.uid() = user_id));



  create policy "users can read own reports"
  on "public"."reports"
  as permissive
  for select
  to public
using ((user_id = auth.uid()));



  create policy "User can see their subscriptions"
  on "public"."subscriptions"
  as permissive
  for select
  to public
using (((auth.uid() = subscriber_id) OR (auth.uid() = creator_id)));



  create policy "Users can subscribe"
  on "public"."subscriptions"
  as permissive
  for insert
  to public
with check ((auth.uid() = subscriber_id));



  create policy "Users can unsubscribe"
  on "public"."subscriptions"
  as permissive
  for delete
  to public
using ((auth.uid() = subscriber_id));



  create policy "Insert topics"
  on "public"."topics"
  as permissive
  for insert
  to public
with check ((EXISTS ( SELECT 1
   FROM public.users u
  WHERE ((u.id = auth.uid()) AND (u.is_creator = true)))));



  create policy "Select topics"
  on "public"."topics"
  as permissive
  for select
  to public
using (true);



  create policy "Update topics"
  on "public"."topics"
  as permissive
  for update
  to public
using ((EXISTS ( SELECT 1
   FROM public.users u
  WHERE ((u.id = auth.uid()) AND (u.is_creator = true)))));



  create policy "Admin can read all users"
  on "public"."users"
  as permissive
  for select
  to public
using (((auth.role() = 'authenticated'::text) AND (is_admin = true)));



  create policy "Admin can update all users"
  on "public"."users"
  as permissive
  for update
  to public
using (((auth.role() = 'authenticated'::text) AND (is_admin = true)));



  create policy "Admin can update users"
  on "public"."users"
  as permissive
  for update
  to public
using ((EXISTS ( SELECT 1
   FROM public.users u
  WHERE ((u.id = auth.uid()) AND (u.is_admin = true)))));



  create policy "Admins cannot delete other admins"
  on "public"."users"
  as permissive
  for delete
  to public
using (((auth.uid() = id) OR (is_admin = false)));



  create policy "Allow insert for authenticated users"
  on "public"."users"
  as permissive
  for insert
  to authenticated
with check (true);



  create policy "Public can read user profiles"
  on "public"."users"
  as permissive
  for select
  to public
using (true);



  create policy "User can view own full profile"
  on "public"."users"
  as permissive
  for select
  to public
using ((auth.uid() = id));



  create policy "Users can read all users"
  on "public"."users"
  as permissive
  for select
  to public
using ((auth.role() = 'authenticated'::text));



  create policy "Users can update own profile"
  on "public"."users"
  as permissive
  for update
  to public
using ((auth.uid() = id));



  create policy "allow insert for owner"
  on "public"."video_parts"
  as permissive
  for insert
  to public
with check (true);



  create policy "allow select for owner"
  on "public"."video_parts"
  as permissive
  for select
  to public
using (true);



  create policy "insert by auth"
  on "public"."video_parts"
  as permissive
  for insert
  to public
with check ((auth.uid() IS NOT NULL));



  create policy "public select"
  on "public"."video_parts"
  as permissive
  for select
  to public
using (true);


CREATE TRIGGER post_comments_count_trigger AFTER INSERT OR DELETE ON public.comments FOR EACH ROW EXECUTE FUNCTION public.update_post_comments_count();

CREATE TRIGGER trigger_increment_comments_count AFTER INSERT ON public.comments FOR EACH ROW EXECUTE FUNCTION public.increment_comments_count();

CREATE TRIGGER trigger_recalc_comments AFTER INSERT OR DELETE OR UPDATE ON public.comments FOR EACH ROW EXECUTE FUNCTION public.recalc_comments_all();

CREATE TRIGGER user_comments_count_trigger AFTER INSERT OR DELETE ON public.comments FOR EACH ROW EXECUTE FUNCTION public.update_user_comments_count();

CREATE TRIGGER trg_sync_creator_request AFTER UPDATE OF status ON public.creator_requests FOR EACH ROW EXECUTE FUNCTION public.sync_creator_request_to_user();

CREATE TRIGGER trigger_sync_creator_status AFTER INSERT OR UPDATE OF status ON public.creator_requests FOR EACH ROW EXECUTE FUNCTION public.sync_creator_status();

CREATE TRIGGER likes_count_trigger AFTER INSERT OR DELETE ON public.likes FOR EACH ROW EXECUTE FUNCTION public.update_post_likes_count();

CREATE TRIGGER trigger_recalc_likes AFTER INSERT OR DELETE OR UPDATE ON public.likes FOR EACH ROW EXECUTE FUNCTION public.recalc_likes_all();

CREATE TRIGGER post_view_delete_trigger AFTER DELETE ON public.post_views FOR EACH ROW EXECUTE FUNCTION public.handle_post_view_delete();

CREATE TRIGGER post_view_insert_trigger AFTER INSERT ON public.post_views FOR EACH ROW EXECUTE FUNCTION public.handle_post_view_insert();

CREATE TRIGGER trigger_recalc_post_views AFTER INSERT OR DELETE OR UPDATE ON public.post_views FOR EACH ROW EXECUTE FUNCTION public.recalc_views_all();

CREATE TRIGGER user_posts_count_trigger AFTER INSERT OR DELETE ON public.posts FOR EACH ROW EXECUTE FUNCTION public.update_user_posts_count();

CREATE TRIGGER subscription_count_trigger AFTER INSERT OR DELETE ON public.subscriptions FOR EACH ROW EXECUTE FUNCTION public.handle_subscription_count();

CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


  create policy "Anyone can upload an avatar."
  on "storage"."objects"
  as permissive
  for insert
  to public
with check ((bucket_id = 'avatars'::text));



  create policy "Avatar images are publicly accessible."
  on "storage"."objects"
  as permissive
  for select
  to public
using ((bucket_id = 'avatars'::text));



